<template>
<v-col style="align-self: center;">


    <v-row style="align: center;">
        <v-col cols="4" style="align-self: center;">
        <v-img
        lazy-src="https://picsum.photos/id/11/10/6"
        max-height="250"
        max-width="250"
        contain
        src="https://www.linkpicture.com/q/2_132.jpg"
        ></v-img>
        <v-col>
          <v-row>
            <v-card-title class="text-h6">
              𝚂𝚝𝚊𝚗𝚍𝚒𝚗𝚐 𝚘𝚞𝚝 𝚒𝚗 𝚝𝚑𝚎 𝚖𝚘𝚘𝚗𝚕𝚒𝚐𝚑𝚝
            </v-card-title>
          </v-row>

          <v-row>
            <v-card-title class="text-subtitle-1">
              By: Manjeet Rafa'el.
            </v-card-title>
            <v-card-title class="text-subtitle-2">
              Genero: Drama.
            </v-card-title>
          </v-row>

        </v-col>

    </v-col>

    <v-col cols="4" style="align-self: center;">
        <v-img
        @click=""
        lazy-src="https://picsum.photos/id/11/10/6"
        max-height="250"
        max-width="250"
        src="https://www.linkpicture.com/q/1_226.jpg"
        ></v-img>
        <v-col>
          <v-row>
            <v-card-title class="text-h6">
              𝘑𝘦𝘴𝘶𝘴: 𝘐𝘯 𝘢 𝘛𝘳𝘢𝘤𝘵𝘰𝘳
            </v-card-title>
          </v-row>

          <v-row>
            <v-card-title class="text-subtitle-1">
              By: Liraz Elly.
            </v-card-title>
            <v-card-title class="text-subtitle-2">
              Genero: Drama Religioso.
            </v-card-title>
          </v-row>

        </v-col>

    </v-col>
    

    <v-col cols="4" style="align-self: center;">
        <v-img
        lazy-src="https://picsum.photos/id/11/10/6"
        max-height="250"
        max-width="250"
        src="https://www.linkpicture.com/q/3_218.jpg"
        ></v-img>
        <v-col>
          <v-row>
            <v-card-title class="text-h6">
              𝘈 𝘴𝘮𝘢𝘭𝘭 𝘤𝘢𝘵 𝘪𝘯 𝘢 𝘣𝘪𝘨 𝘸𝘰𝘳𝘭𝘥
            </v-card-title>
          </v-row>

          <v-row>
            <v-card-title class="text-subtitle-1">
              By: Shamil Nanna.
            </v-card-title>
            <v-card-title class="text-subtitle-2">
              Genero: Infantil.
            </v-card-title>
          </v-row>


        </v-col>

    </v-col>
        
    </v-row>

    <v-row style="align: center;">
        <v-col cols="4" style="align-self: center;">
        <v-img
        lazy-src="https://picsum.photos/id/11/10/6"
        max-height="250"
        max-width="250"
        contain
        src="https://www.linkpicture.com/q/4_132.jpg"
        ></v-img>
        <v-col>
          <v-row>
            <v-card-title class="text-h6">
              𝘈 𝘣𝘳𝘪𝘨𝘩𝘵 𝘯𝘦𝘸 𝘸𝘰𝘳𝘭𝘥
            </v-card-title>
          </v-row>

            <v-row>
              <v-card-title class="text-subtitle-1">
              By: Helena Sabrina.
            </v-card-title>
            <v-card-title class="text-subtitle-2">
              Genero: Fantasia.
            </v-card-title>
            </v-row>

        </v-col>
     

    </v-col>

    <v-col cols="4" style="align-self: center;">
        <v-img
        lazy-src="https://picsum.photos/id/11/10/6"
        max-height="250"
        max-width="250"
        src="https://www.linkpicture.com/q/5_55.jpg"
        ></v-img>
          <v-col>
            <v-row>
              <v-card-title class="text-h6">
                𝘚𝘶𝘮 𝘤𝘢𝘵𝘻 4 𝘶 & 𝘮𝘦
            </v-card-title>
            </v-row>

            <v-row>
              <v-card-title class="text-subtitle-1">
              By: Vaiva Lutgard.
            </v-card-title>
            <v-card-title class="text-subtitle-2">
              Genero: Infantil.
            </v-card-title>
            </v-row>

        </v-col>
     

    </v-col>
    

    <v-col cols="4" style="align-self: center;">
        <v-img
        lazy-src="https://picsum.photos/id/11/10/6"
        max-height="250"
        max-width="250"
        src="https://www.linkpicture.com/q/6_4.jpg"
        ></v-img>
        <v-col>
          <v-row>
            <v-card-title class="text-h6">
              𝘔𝘦𝘭𝘵𝘪𝘯𝘨 𝘧𝘰𝘳 𝘺𝘰𝘶: 𝘈 𝘭𝘰𝘷𝘦 𝘴𝘵𝘰𝘳𝘺
            </v-card-title>
          </v-row>
      
            <v-row>
              <v-card-title class="text-subtitle-1">
              By: Rufus Samuel.
            </v-card-title>
            <v-card-title class="text-subtitle-2">
              Genero: Romance.
            </v-card-title>
            </v-row>
        </v-col>

    </v-col>
        
    </v-row>

    <v-row style="align: center;">
        <v-col cols="4" style="align-self: center;">
        <v-img
        lazy-src="https://picsum.photos/id/11/10/6"
        max-height="250"
        max-width="250"
        contain
        src="https://www.linkpicture.com/q/7_12.jpg"
        ></v-img>
        <v-col>
          <v-row>
            <v-card-title class="text-h6">
              𝘎𝘰𝘭𝘧𝘪𝘯𝘨 101 𝘧𝘰𝘳 1 𝘰𝘯𝘦 𝘦𝘺𝘦𝘥 𝘱𝘦𝘰𝘱𝘭𝘦
            </v-card-title>
          </v-row>
         
            <v-row>
              <v-card-title class="text-subtitle-1">
              By: Louise Alve.
            </v-card-title>
            <v-card-title class="text-subtitle-2">
              Genero: Educativo.
            </v-card-title>
            </v-row>
        </v-col>

    </v-col>

    <v-col cols="4" style="align-self: center;">
        <v-img
        lazy-src="https://picsum.photos/id/11/10/6"
        max-height="250"
        max-width="250"
        src="https://www.linkpicture.com/q/8_9.jpg"
        ></v-img>
        <v-col >
          <v-row>
            <v-card-title class="text-h6">
              𝘋𝘳𝘦𝘢𝘮𝘴 𝘰𝘧 𝘢 𝘵𝘩𝘰𝘰𝘵 𝘧𝘢𝘪𝘳𝘺
            </v-card-title>
          </v-row>

           <v-row>
            <v-card-title class="text-subtitle-1">
              By: Céfiro Tylor.
            </v-card-title>
            <v-card-title class="text-subtitle-2">
              Genero: Fantasia.
            </v-card-title>
           </v-row>
        </v-col>

    </v-col>
    

    <v-col cols="4" style="align-self: center;">
        <v-img
        lazy-src="https://picsum.photos/id/11/10/6"
        max-height="250"
        max-width="250"
        src="https://www.linkpicture.com/q/9_9.jpg"
        ></v-img>
        <v-col>
          <v-row>
            <v-card-title class="text-h6">
              𝘞𝘩𝘦𝘯 𝘵𝘩𝘦 𝘴𝘶𝘯 𝘨𝘰𝘦𝘴 𝘰𝘶𝘵
            </v-card-title>
          </v-row>
            <v-row>
              <v-card-title class="text-subtitle-1">
              By: Vihaan Wīgaberhtaz.
            </v-card-title>
            <v-card-title class="text-subtitle-2">
              Genero: Horror.
            </v-card-title>
            </v-row>

        </v-col>

    </v-col>
        
    </v-row>





</v-col>

  </template>