<template>
<v-col style="align-self: center;">


    <v-row style="align: center;">
        <v-col cols="4" style="align-self: center;">
        <v-img
        lazy-src="https://picsum.photos/id/11/10/6"
        max-height="250"
        max-width="250"
        contain
        src="https://www.linkpicture.com/q/2_132.jpg"
        ></v-img>
        <v-col>
          <v-row>
            <v-card-title class="text-h6">
              Standing out in the moonlight
            </v-card-title>
          </v-row>

            <v-card-title class="text-subtitle-1">
              By: Manjeet Rafa'el.
            </v-card-title>
            <v-card-title class="text-subtitle-2">
              Genero: Drama.
            </v-card-title>
        </v-col>

    </v-col>

    <v-col cols="4" style="align-self: center;">
        <v-img
        lazy-src="https://picsum.photos/id/11/10/6"
        max-height="250"
        max-width="250"
        src="https://www.linkpicture.com/q/1_226.jpg"
        ></v-img>
        <v-col>
          <v-row>
            <v-card-title class="text-h6">
              Jesus: In a Tractor
            </v-card-title>
          </v-row>

            <v-card-title class="text-subtitle-1">
              By: Liraz Elly.
            </v-card-title>
            <v-card-title class="text-subtitle-2">
              Genero: Drama Religioso.
            </v-card-title>
        </v-col>

    </v-col>
    

    <v-col cols="4" style="align-self: center;">
        <v-img
        lazy-src="https://picsum.photos/id/11/10/6"
        max-height="250"
        max-width="250"
        src="https://www.linkpicture.com/q/3_218.jpg"
        ></v-img>
        <v-col>
          <v-row>
            <v-card-title class="text-h6">
              A small cat in a big world
            </v-card-title>
          </v-row>

            <v-card-title class="text-subtitle-1">
              By: Shamil Nanna.
            </v-card-title>
            <v-card-title class="text-subtitle-2">
              Genero: Infantil.
            </v-card-title>
        </v-col>

    </v-col>
        
    </v-row>

    <v-row style="align: center;">
        <v-col cols="4" style="align-self: center;">
        <v-img
        lazy-src="https://picsum.photos/id/11/10/6"
        max-height="250"
        max-width="250"
        contain
        src="https://www.linkpicture.com/q/4_132.jpg"
        ></v-img>
        <v-col>
          <v-row>
            <v-card-title class="text-h6">
              A bright new world
            </v-card-title>
          </v-row>

              <v-card-title class="text-subtitle-1">
              By: Helena Sabrina.
            </v-card-title>
            <v-card-title class="text-subtitle-2">
              Genero: Fantasia.
            </v-card-title>

        </v-col>
     

    </v-col>

    <v-col cols="4" style="align-self: center;">
        <v-img
        lazy-src="https://picsum.photos/id/11/10/6"
        max-height="250"
        max-width="250"
        src="https://www.linkpicture.com/q/5_55.jpg"
        ></v-img>
          <v-col>
            <v-row>
              <v-card-title class="text-h6">
              Sum catz 4 u & me
            </v-card-title>
            </v-row>


              <v-card-title class="text-subtitle-1">
              By: Vaiva Lutgard.
            </v-card-title>
            <v-card-title class="text-subtitle-2">
              Genero: Infantil.
            </v-card-title>


        </v-col>
     

    </v-col>
    

    <v-col cols="4" style="align-self: center;">
        <v-img
        lazy-src="https://picsum.photos/id/11/10/6"
        max-height="250"
        max-width="250"
        src="https://www.linkpicture.com/q/6_4.jpg"
        ></v-img>
        <v-col>
          <v-row>
            <v-card-title class="text-h6">
              Melting for you: A love story
            </v-card-title>
          </v-row>
      

              <v-card-title class="text-subtitle-1">
              By: Rufus Samuel.
            </v-card-title>
            <v-card-title class="text-subtitle-2">
              Genero: Romance.
            </v-card-title>

        </v-col>

    </v-col>
        
    </v-row>

    <v-row style="align: center;">
        <v-col cols="4" style="align-self: center;">
        <v-img
        lazy-src="https://picsum.photos/id/11/10/6"
        max-height="250"
        max-width="250"
        contain
        src="https://www.linkpicture.com/q/7_12.jpg"
        ></v-img>
        <v-col>
          <v-row>
            <v-card-title class="text-h6">
              Golfing 101 for 1 one eyed people
            </v-card-title>
          </v-row>
         

              <v-card-title class="text-subtitle-1">
              By: Louise Alve.
            </v-card-title>
            <v-card-title class="text-subtitle-2">
              Genero: Educativo.
            </v-card-title>

        </v-col>

    </v-col>

    <v-col cols="4" style="align-self: center;">
        <v-img
        lazy-src="https://picsum.photos/id/11/10/6"
        max-height="250"
        max-width="250"
        src="https://www.linkpicture.com/q/8_9.jpg"
        ></v-img>
        <v-col >
          <v-row>
            <v-card-title class="text-h6">
             Dreams of a thoot fairy
            </v-card-title>
          </v-row>


            <v-card-title class="text-subtitle-1">
              By: Céfiro Tylor.
            </v-card-title>
            <v-card-title class="text-subtitle-2">
              Genero: Fantasia.
            </v-card-title>

        </v-col>

    </v-col>
    

    <v-col cols="4" style="align-self: center;">
        <v-img
        lazy-src="https://picsum.photos/id/11/10/6"
        max-height="250"
        max-width="250"
        src="https://www.linkpicture.com/q/9_9.jpg"
        ></v-img>
        <v-col>
          <v-row>
            <v-card-title class="text-h6">
             When the sun goes out
            </v-card-title>
          </v-row>
 
              <v-card-title class="text-subtitle-1">
              By: Vihaan Wīgaberhtaz.
            </v-card-title>
            <v-card-title class="text-subtitle-2">
              Genero: Horror.
            </v-card-title>


        </v-col>

    </v-col>
        
    </v-row>





</v-col>

  </template>